### PR TITLE
Compatibility issues with cypress 4.0

### PR DESCRIPTION
**Pull request by rnikkels**
the current version on cypress will no longer support the plugin. plz review these small changes

### CODE REVIEW

**Comment by lots0logs** [comment]
This is a duplicate of #91

**Comment by rnikkels** [comment]
You are correct, closing this one

**Comment by meinaart** [comment]
Hello mister Nikkels ;). Thanks for contributing.

**Comment by rnikkels** [comment]
Yo Meinaart, can you release it on NPM as well? Or am I just to hasty? :)

**Comment by meinaart** [comment]
It's released now :)

**Comment by rnikkels** [comment]
Tnx man :)

**Pull request closed without merging**
