### PR TITLE
Fix cypress peer dependency to includ version higher than 4

### LINKED ISSUE #183: Cypress Peer Dependency
will the Cypress Peer Dependency get update? i see its still on 4.5.0 which is very old.

### PR DESCRIPTION
**Pull request by Izhaki**
Fixes #183

### CODE REVIEW

**Review by joetidee — APPROVED** [review]

**Comment by ozkoidi** [comment]
Could someone merge this please? Is a **one line** change to fix an issue that has been opened for **10 months**

**Comment by lukasvida** [comment]
.

**Comment by AlexanderTunick** [comment]
Any ETA on this dependency? This warning pisses me off every time when I need to use npm install.

**Review by matano-dev — APPROVED** [review]

**Comment by theochp** [comment]
@meinaart is this repo still maintained by you ?

**Comment by meinaart** [comment]
> @meinaart is this repo still maintained by you ?

Officially yes. But I don’t have time for it. I would welcome additional maintainers.

**Pull request merged**
